# .claude-yo.yml - xplat project Docker environment

# System packages installed via apt-get
apt:
  - python3
  - python3-pip
  - python3-venv
  - git
  - curl

# Python packages - install Poetry via pip
pip:
  - poetry
